CREATE SCHEMA saga;

CREATE TABLE saga.MESSAGE_RELAY(
	idMessage int IDENTITY(1,1) NOT NULL,
	idSaga VARCHAR(100) NOT NULL,
	name varchar(255) NOT NULL,
	time DATETIME NOT NULL,
	data TEXT NOT NULL,
	status VARCHAR(100) NOT NULL,
	saga VARCHAR(255) NOT NULL,
	CONSTRAINT MESSAGE_RELAY_pk PRIMARY KEY (idMessage)
);